# Generated by Django 2.0.13 on 2019-07-03 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='data',
            name='ipaddress',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='IPアドレス'),
        ),
        migrations.AlterField(
            model_name='data',
            name='content',
            field=models.TextField(verbose_name='本文'),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=200, verbose_name='投稿者名'),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日時'),
        ),
    ]
