# Generated by Django 2.0.13 on 2019-07-04 00:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190703_0934'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='data',
            name='person_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='ipaddress',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 4, 0, 46, 58, 219093, tzinfo=utc)),
        ),
    ]
